baseurl = "https://www.thesubtlety.com/"
languageCode = "en-us"
title = "The Subtlety"
canonifyurls = "true"
googleAnalytics = "UA-29425132-1"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Indiscriminate Idiotropics on Infosec"
  AuthorName = "Noah"
  googleAnalytics = "UA-29425132-1"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
