baseurl = "https://www.thesubtlety.com"
languageCode = "en-us"
title = "The Subtlety"
canonifyurls = "false"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Indiscriminate Idiotropics on Infosec"
  AuthorName = "Noah"
  google_analytics_tracking_id = "UA-29425132-1"
